task_new:
    path: /new
    defaults: { _controller: "AppBundle:Task:new" }
    methods: POST

task_edit:
    path: /edit/{id}
    defaults: { _controller: "AppBundle:Task:new", id:null }
    methods: POST

task_list:
    path: /list
    defaults: { _controller: "AppBundle:Task:tasks" }
    methods: POST